# This file was auto-generated by the electric-cli `./_tap.sh` script.
# DO NOT EDIT MANUALLY.

class ElectricCli < Formula
  include Language::Python::Virtualenv

  desc "ElectricDB command line interface utility."
  homepage "https://electricdb.net"
  license "MIT"
  version "0.0.3"

  url "https://pypi.io/packages/source/e/electric-db-cli/electric-db-cli-0.0.3.tar.gz"
  sha256 "bbcd6e56ce2d810173db31e8629a8952a8d0afbb9437cea7da44cfd63810899f"
  head "https://github.com/electric-db/electric-cli.git"

  resource "certifi" do
    url "https://pypi.io/packages/source/c/certifi/certifi-2021.10.8.tar.gz"
    sha256 "78884e7c1d4b00ce3cea67b44566851c4343c120abd683433ce934a68ea58872"
  end
  resource "charset-normalizer" do
    url "https://pypi.io/packages/source/c/charset-normalizer/charset-normalizer-2.0.7.tar.gz"
    sha256 "e019de665e2bcf9c2b64e2e5aa025fa991da8720daa3c1138cadd2fd1856aed0"
  end
  resource "click" do
    url "https://pypi.io/packages/source/c/click/click-7.1.2.tar.gz"
    sha256 "d2b5255c7c6349bc1bd1e59e08cd12acbbd63ce649f2588755783aa94dfb6b1a"
  end
  resource "durations" do
    url "https://pypi.io/packages/source/d/durations/durations-0.3.3.tar.gz"
    sha256 "820ffe09c390469dc621b6a0aa46d3a624b6dadf09b439e175696b6f6b77ef2f"
  end
  resource "idna" do
    url "https://pypi.io/packages/source/i/idna/idna-3.3.tar.gz"
    sha256 "9d643ff0a55b762d5cdb124b8eaa99c66322e2157b69160bc32796e824360e6d"
  end
  resource "requests" do
    url "https://pypi.io/packages/source/r/requests/requests-2.26.0.tar.gz"
    sha256 "b8aa58f8cf793ffd8782d3d8cb19e66ef36f7aba4353eec859e74678b01b07a7"
  end
  resource "sparse" do
    url "https://pypi.io/packages/source/s/sparse/sparse-0.0.1.tar.gz"
    sha256 "c5eaaae55ad58c3c98acd3008b6ee022b88b5da15cfc4dba9b1a10ba7a30835b"
  end
  resource "sparse-cli" do
    url "https://pypi.io/packages/source/s/sparse-cli/sparse-cli-0.0.2.tar.gz"
    sha256 "bd5f675954125f95b5fbcc8d8188d30d3ccf1a51e1bc719e7160e8f17879ba95"
  end
  resource "urllib3" do
    url "https://pypi.io/packages/source/u/urllib3/urllib3-1.26.7.tar.gz"
    sha256 "4987c65554f7a2dbf30c18fd48778ef124af6fab771a377103da0585e2336ece"
  end

  depends_on "python@3"

  def install
    virtualenv_install_with_resources(:using => "python@3")
  end
end
